name: jahandigital
description: "A new Flutter project."

publish_to: "none"

version: 1.0.7+8

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  get: ^4.7.3
  http: ^1.1.0
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  fluttertoast: ^9.0.0
  get_storage: ^2.1.1
  easy_localization: ^3.0.7
  flutter_timezone: ^5.0.1
  timezone_utc_offset: ^1.1.0
  cached_network_image: ^3.3.1
  lottie: ^3.1.2
  share_plus: ^12.0.0
  path_provider: ^2.1.3
  image: ^4.1.6
  # permission_handler: ^11.0.1
  change_app_package_name: ^1.4.0
  connectivity_plus: ^6.0.5
  flutter_launcher_icons: ^0.14.3
  url_launcher: ^6.3.1
  intl: ^0.20.2
  image_gallery_saver_plus: ^4.0.1
  in_app_update: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "assets/icons/logo.png"

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/langs/en-US.json
    - assets/langs/bn-BD.json
    - assets/langs/fa-IR.json
    - assets/langs/ar-AE.json
    - assets/langs/ps-AF.json
    - assets/langs/tr-TR.json
    - assets/loties/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto.ttf

    - family: Iranfont
      fonts:
        - asset: assets/fonts/iranfont.ttf

    - family: Iranfont
      fonts:
        - asset: assets/fonts/iranyekanregular.ttf

    - family: Iranfont
      fonts:
        - asset: assets/fonts/iranyekanbold.ttf
